sonar.projectKey=VidiomTM_lean-runtime-analysis
sonar.organization=VidiomTM
sonar.projectName=lean-runtime-analysis

sonar.sources=.
sonar.exclusions=.lake/**,**/*.bak

sonar.sourceEncoding=UTF-8
sonar.language=generic

sonar.cpd.exclusions=.lake/**,**/*.bak,**/lake-manifest.json,**/lakefile.lean

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
